software:
  name: "Debian"
  description: "Debian Linux OS for cloud and server environments."
  fixed_components:
    - name: "Primary Compute Unit"
      type: "compute"
      compute_requirements:
        vcpu: 4
        memory_gb: 16
        storage_gb: 100
      cloud_skus:
        aws: "m5.xlarge"
        gcp: "n1-standard-4"
        azure: "D4s_v3"
    - name: "Storage"
      type: "storage"
      storage_requirements:
        storage_gb: 100
      cloud_skus:
        aws: "general_purpose_ssd"
        gcp: "standard_persistent_disk"
        azure: "standard_persistent_disk"
