software:
  name: "Debian Web Server"
  description: "Deployment of a Debian-based web server."

  fixed_components:
    - name: "Web Server Instance"
      type: "compute"
      compute_requirements:
        vcpu: 2
        memory_gb: 4
        storage_gb: 50
      cloud_skus:
        aws: "t3a.large"
        gcp: "n1-standard-2"
        azure: "B2s"
    - name: "Storage"
      type: "storage"
      storage_requirements:
        storage_gb: 50
      cloud_skus:
        aws: "gp2"
        gcp: "standard_persistent_disk"
        azure: "StandardSSD_LRS"

  variable_components:
    - name: "Web Traffic"
      average_vcpu_per_user: 0.0005
      average_memory_per_user_gb: 0.001
      storage_per_user_gb: 0.0005

  variable_growth: "linear"
  scaling_factor: 1
