software:
  name: "GitLab"
  description: "Self-managed GitLab instance with CI/CD capabilities."
  fixed_components:
    - name: "Primary Compute Unit"
      type: "compute"
      compute_requirements:
        vcpu: 8  # Fixed to match the GitLab recommendation
        memory_gb: 16  # Memory per GitLab recommendation
        storage_gb: 500  # Increased to handle repositories and data

  variable_components:
    - name: "CI/CD Runners"
      type: "variable-compute"
      user_inputs:
        users: 1000
        workload: "medium"
        activity: "moderate"
      usage_profiles:
        medium:
          light:
            average_vcpu_per_user: 0.03  # Adjusted to reflect CI/CD resource usage
            average_memory_per_user_gb: 0.1
            storage_per_user_gb: 5
          moderate:
            average_vcpu_per_user: 0.05  # Adjusted based on GitLab's actual architecture
            average_memory_per_user_gb: 0.2
            storage_per_user_gb: 10
          heavy:
            average_vcpu_per_user: 0.1
            average_memory_per_user_gb: 0.5
            storage_per_user_gb: 15
