software:
  name: "GitLab"
  description: "Self-managed GitLab instance with CI/CD capabilities."

  fixed_components:
    - name: "Primary Compute Unit"
      type: "compute"
      compute_requirements:
        vcpu: 8
        memory_gb: 16
        storage_gb: 100
      cloud_skus:
        aws: "c5.2xlarge"
        gcp: "n1-standard-8"
        azure: "F8s_v2"
    - name: "Storage"
      type: "storage"
      storage_requirements:
        storage_gb: 100
      cloud_skus:
        aws: "general_purpose_ssd"
        gcp: "standard_persistent_disk"
        azure: "StandardSSD_LRS"

  variable_components:
    - name: "User Load"
      average_vcpu_per_user: 0.5
      average_memory_per_user_gb: 1
      storage_per_user_gb: 5

  variable_growth: "linear"  # Options: linear, superlinear, sublinear, power
  scaling_factor: 1  # Scaling factor for the variable growth
