software:
  name: "NVIDIA Deep Learning"
  description: "Deployment of NVIDIA GPU-accelerated machine learning workloads."

  fixed_components:
    - name: "GPU Compute Instance"
      type: "compute"
      compute_requirements:
        vcpu: 16
        memory_gb: 64
        storage_gb: 1000
      cloud_skus:
        aws: "p3.2xlarge"
        gcp: "n1-highmem-16"
        azure: "NC6s_v3"
    - name: "Storage"
      type: "storage"
      storage_requirements:
        storage_gb: 1000
      cloud_skus:
        aws: "provisioned_iops_ssd"
        gcp: "ssd_persistent_disk"
        azure: "PremiumSSD_LRS"

  gpu_requirements:
    - name: "NVIDIA GPUs"
      gpu_requirements:
        gpu_count: 1
        gpu_memory_gb: 16
      cloud_skus:
        aws: "Tesla V100"
        gcp: "nvidia-tesla-v100"
        azure: "NVIDIA V100"

  variable_components:
    - name: "Model Training Load"
      average_vcpu_per_user: 2
      average_memory_per_user_gb: 8
      storage_per_user_gb: 50

  variable_growth: "superlinear"  # Options: linear, superlinear, sublinear, power
  scaling_factor: 1.05  # Scaling factor for the variable growth
