software:
  name: "Windows Server"
  description: "Deployment of a Windows Server instance with license."

  fixed_components:
    - name: "Windows Server Instance"
      type: "compute"
      compute_requirements:
        vcpu: 8
        memory_gb: 32
        storage_gb: 500
      cloud_skus:
        aws: "m5.2xlarge.windows"
        gcp: "n1-standard-8-windows"
        azure: "D8s_v3"

    - name: "Storage"
      type: "storage"
      storage_requirements:
        storage_gb: 500
      cloud_skus:
        aws: "gp2"
        gcp: "standard_persistent_disk"
        azure: "StandardSSD_LRS"

  variable_components:
    - name: "Windows Workload"
      average_vcpu_per_user: 0.005
      average_memory_per_user_gb: 0.01
      storage_per_user_gb: 0.005

  variable_growth: "linear"
  scaling_factor: 1
